#lang racket
(require racket/set)
(require data/heap)
(struct graph (node adj_list weights) #:mutable)
(provide initialize_graph)
(define (initialize_graph)
  (graph empty (make-hash) (make-hash))
  )
(provide add_node)
(define (add_node grph node_)
  (set-graph-node! grph (cons node_ (graph-node grph)))   
  )
(provide add_edge)
(define (add_edge grph u v w)
  (set-add! (hash-ref! (graph-adj_list grph) u (mutable-set)) v)
  (set-add! (hash-ref! (graph-adj_list grph) v (mutable-set)) u)
  (hash-set! (hash-ref! (graph-weights grph) u (make-hash)) v w)
  (hash-set! (hash-ref! (graph-weights grph) v (make-hash)) u w)
  )
(provide displn)
(define (displn a)
  (display a)
  (display "\n")
  )
(define (get_weight grph u v)
  (hash-ref (hash-ref (graph-weights grph) u) v)
  )
(define (getVal hash key) ; change getVal
  (hash-ref hash key)
  )
(define (setVal hash key val)
  (hash-set! hash key val)
  )
(define (comp x y)
  (<= (car x) (car y))
  )
(define (heap-empty? heap)
  (= 0 (heap-count heap))
  )
(define inf 20000000000) ; define inf 'inf 
(define (djikstra grph u v)
  (let ([isVisited (make-hash (map (lambda (x) (cons x 'notvisited)) (graph-node grph)))] 
        [distance (make-hash (map (lambda (x) (if (equal? x u) (cons x 0) (cons x inf))) (graph-node grph)))]
        [minHeap (make-heap comp)]) 
    (heap-add! minHeap (cons (getVal distance u) u))
    (define (check)
      (cond
        [(heap-empty? minHeap) (void)]
        [else (let ([top (heap-min minHeap)])
                (heap-remove-min! minHeap)
                (cond
                  [(equal? 'visited (hash-ref isVisited (cdr top))) (void)]
                  [else
                   (set-for-each (hash-ref (graph-adj_list grph) (cdr top))
                   (lambda (x) 
                          (cond
                            [(< (+ (getVal distance (cdr top)) (get_weight grph (cdr top) x)) (getVal distance x))
                              (setVal distance x (+ (getVal distance (cdr top)) (get_weight grph (cdr top) x)))(heap-add! minHeap (cons (getVal distance x) x))]
                             ))
                        ) (setVal isVisited (cdr top) 'visited) (check)]) (void))])) (check) distance
      ) 
  ) 
(provide shortest_path)
 (define (shortest_path grph src dst)
   (let ([distance (djikstra grph src dst)])
     (display "All distances :")
     (displn distance)
   (getVal (djikstra grph src dst) dst)
   )
   )
(provide print_graph)
(define (print_graph grph)
  (display "\nNodes: ")
  (display (graph-node grph))
  (display "\n")
  (display "Adjacency List: ")
  (display (graph-adj_list grph))
  (display "\nWeights: ")
  (displn (graph-weights grph)) 
  )  

