#lang racket
(require "graph.rkt")
(define a (initialize_graph))
(add_node a #\A)
(add_node a #\B)
(add_node a #\C)
(add_node a #\D)
(add_node a #\E)
(add_edge a #\A #\C 1)
(add_edge a #\A #\B 3)
(add_edge a #\B #\C 7)
(add_edge a #\B #\D 5)
(add_edge a #\B #\E 1)
(add_edge a #\D #\E 7)
(add_edge a #\C #\D 2)
(print_graph a)
(display (shortest_path a #\A #\B))
