#lang racket
(require "graph.rkt")
(define a (initialize_graph))
(add_node a 1)
(add_node a 2)
(add_node a 3)
(add_node a 4)
(add_edge a 1 2 24)
(add_edge a 1 3 3)
(add_edge a 1 4 20)
(add_edge a 3 4 12)
(display (shortest_path a 1 2))